### ISSUE TITLE
Task: Initialize React Native Project

### ISSUE THREAD

**Issue by chriscoderdr** [chriscoderdr/DoItMorro#23]
# Task: Initialize React Native Project

## Description
Set up a new React Native project to serve as the frontend for the DoItMorro app. This task includes initializing the project, installing dependencies, and configuring it for Firebase integration.

## Labels
- **mobile-app**
- **firebase-integration**
- **task-management**

## Checklist
- [ ] **Set Up React Native Project**:
  - Use Expo or bare React Native to initialize the project:
    ```bash
    npx expo init doit-morro-app
    ```
  - If TypeScript is required, choose the template for TypeScript during setup or add it manually:
    ```bash
    expo install typescript
    ```

- [ ] **Install Dependencies**:
  - Add Firebase and state management libraries:
    ```bash
    expo install firebase react-redux @reduxjs/toolkit redux-persist
    ```
  - If necessary, install additional libraries for navigation:
    ```bash
    expo install @react-navigation/native react-native-screens react-native-safe-area-context react-native-gesture-handler react-native-reanimated react-native-get-random-values
    ```

- [ ] **Configure Project for TypeScript (Optional)**:
  - Ensure `tsconfig.json` is present and properly configured:
    ```json
    {
      "compilerOptions": {
        "target": "esnext",
        "module": "commonjs",
        "strict": true,
        "jsx": "react-native",
        "esModuleInterop": true,
        "skipLibCheck": true,
        "baseUrl": "./",
        "paths": {
          "@/*": ["src/*"]
        }
      }
    }
    ```
  - Rename `.js` files to `.tsx` where necessary.

- [ ] **Verify Project Setup**:
  - Run the project to ensure proper setup:
    ```bash
    npx expo start
    ```
  - Check for any errors or warnings and resolve them.

## Dependencies
- Related to #24.

## Notes
- Use Expo's official documentation for guidance: [Expo Documentation](https://docs.expo.dev/).
- Ensure dependencies are compatible with the Expo version in use.
