### ISSUE TITLE
Task: Add Firebase Configuration

### ISSUE THREAD

**Issue by chriscoderdr** [chriscoderdr/DoItMorro#24]
# Task: Add Firebase Configuration

## Description
Set up Firebase for the DoItMorro app by creating a Firebase project, configuring it for mobile apps, and integrating it with the React Native frontend.

## Labels
- **mobile-app**
- **firebase-integration**

## Checklist
- [ ] **Create Firebase Project**:
  - Go to the [Firebase Console](https://console.firebase.google.com/).
  - Create a new project and configure it for web, iOS, and Android.

- [ ] **Download Configuration Files**:
  - Download `google-services.json` for Android and `GoogleService-Info.plist` for iOS.
  - Place the files in their respective locations:
    ```
    /android/app/google-services.json
    /ios/<project-name>/GoogleService-Info.plist
    ```

- [ ] **Initialize Firebase in App**:
  - Add the Firebase configuration to the project:
    ```javascript
    import { initializeApp } from "firebase/app";

    const firebaseConfig = {
      apiKey: "your-api-key",
      authDomain: "your-app.firebaseapp.com",
      projectId: "your-project-id",
      storageBucket: "your-app.appspot.com",
      messagingSenderId: "your-messaging-sender-id",
      appId: "your-app-id",
    };

    const app = initializeApp(firebaseConfig);
    ```

- [ ] **Test Firebase Setup**:
  - Verify Firebase is initialized successfully by using any Firebase feature, such as Authentication:
    ```javascript
    import { getAuth } from "firebase/auth";
    const auth = getAuth(app);
    console.log("Firebase Auth initialized:", auth);
    ```

## Dependencies
- Related to #23.

## Notes
- Ensure Firebase configuration keys are stored securely and not exposed in version control.
- Reference Firebase's official documentation for guidance: [Firebase Setup for React Native](https://firebase.google.com/docs/web/setup).
