### ISSUE TITLE
Task: Manage Authentication State

### ISSUE THREAD

**Issue by chriscoderdr** [chriscoderdr/DoItMorro#27]
# Task: Manage Authentication State

## Description
Implement authentication state management using Redux and Redux Persist to store and persist user login status across app sessions.

## Labels
- **mobile-app**
- **state-management**
- **authentication**

## Checklist
- [ ] **Add Redux and Redux Persist Configuration**:
  - Create a Redux store with authentication-related state fields (`isLoggedIn` and `user`).
  - Configure `redux-persist` to persist the Redux store in `AsyncStorage`.

- [ ] **Integrate Firebase Authentication**:
  - Use Firebase's `onAuthStateChanged` to sync authentication state with the Redux store:
    ```javascript
    import { getAuth, onAuthStateChanged } from "firebase/auth";
    import { store } from "./redux/store";
    import { setUser, clearUser } from "./redux/authSlice";

    const auth = getAuth();
    onAuthStateChanged(auth, (user) => {
      if (user) {
        store.dispatch(setUser(user));
      } else {
        store.dispatch(clearUser());
      }
    });
    ```

- [ ] **Persist Authentication State**:
  - Ensure `redux-persist` saves the user's authentication status and restores it on app launch:
    ```javascript
    import AsyncStorage from "@react-native-async-storage/async-storage";
    import { persistReducer, persistStore } from "redux-persist";

    const persistConfig = {
      key: "auth",
      storage: AsyncStorage,
    };

    const persistedReducer = persistReducer(persistConfig, authReducer);
    ```

- [ ] **Test Authentication State Management**:
  - Verify the user's state is updated correctly on login, logout, and app relaunch.

## Dependencies
- Related to #24.

## Notes
- Ensure secure storage practices for user-sensitive information.
- Reference Redux Toolkit and Redux Persist documentation for best practices:
  - [Redux Toolkit](https://redux-toolkit.js.org/)
  - [Redux Persist](https://github.com/rt2zz/redux-persist).
