### ISSUE TITLE
Task: Integrate Edit To-Do Functionality

### ISSUE THREAD

**Issue by chriscoderdr** [chriscoderdr/DoItMorro#29]
# Task: Implement Edit To-Do Functionality

## Description
Implement the functionality to allow users to edit an existing to-do item. This includes updating the title, description, and due date through the app's UI, validating inputs, saving changes to the database via the API, and ensuring updated details are displayed in the to-do list.

## Labels
- **task-management**
- **mobile-app**
- **api**

### Feature/Functionality Implementation
- [ ] **Enable/Configure Necessary Services**:
  - Ensure the Koa.js API is configured to handle `PUT` requests for editing to-dos.
  - Confirm Sequelize models and migrations support updates to `title`, `description`, and `dueDate` fields.

- [ ] **Write Core Functionality**:
  - Add the `/todos/:id` endpoint in the Koa.js backend:
    ```javascript
    router.put('/todos/:id', async (ctx) => {
      const { title, description, dueDate } = ctx.request.body;
      const todoId = ctx.params.id;

      if (!title) {
        ctx.status = 400;
        ctx.body = { error: 'Title is required' };
        return;
      }

      const updatedTodo = await Todo.update(
        { title, description, dueDate },
        { where: { id: todoId, userId: ctx.state.user.id }, returning: true }
      );

      if (!updatedTodo[1][0]) {
        ctx.status = 404;
        ctx.body = { error: 'To-Do not found' };
        return;
      }

      ctx.status = 200;
      ctx.body = updatedTodo[1][0];
    });
    ```

  - Integrate the edit functionality in the mobile app using RTK Query:
    ```javascript
    export const todosApi = createApi({
      reducerPath: 'todosApi',
      baseQuery: fetchBaseQuery({ baseUrl: '/api' }),
      endpoints: (builder) => ({
        updateTodo: builder.mutation({
          query: ({ id, data }) => ({
            url: `/todos/${id}`,
            method: 'PUT',
            body: data,
          }),
        }),
      }),
    });

    export const { useUpdateTodoMutation } = todosApi;
    ```

  - Use the `useUpdateTodoMutation` hook in the edit form component:
    ```javascript
    const [updateTodo, { isLoading, error }] = useUpdateTodoMutation();

    const handleEditSubmit = async (id, data) => {
      try {
        const result = await updateTodo({ id, data }).unwrap();
        alert('To-Do updated successfully!');
      } catch (err) {
        console.error('Failed to update To-Do:', err);
      }
    };
    ```

### Error Handling
- [ ] **Handle and Map Errors**:
  - Map server errors (e.g., missing `title`, invalid `id`) to user-friendly error messages.
  - Handle cases where the to-do does not exist (`404` response).

### Integration with State Management
- [ ] **Dispatch Redux Actions**:
  - Update the Redux store with the updated to-do details upon a successful API response.
    ```javascript
    store.dispatch(updateTodoAction(updatedTodo));
    ```

### User Feedback
- [ ] **Provide Feedback on Operation Status**:
  - Display loading indicators during the API call.
  - Show success or error messages based on the result of the edit operation.

### Testing
- [ ] **Unit Testing**:
  - Test the API endpoint with mock data to validate functionality.
  - Use mock hooks to test the `useUpdateTodoMutation` behavior.
- [ ] **Integration Testing**:
  - Verify that the Redux state is updated correctly after a successful edit operation.
- [ ] **End-to-End Testing**:
  - Simulate user flows to validate the entire editing process, from opening the edit form to saving changes.

### Verification
- [ ] **Verify State Management Integration**:
  - Ensure the updated details are reflected in the to-do list immediately after the edit operation.
- [ ] **Check Platform Compatibility**:
  - Test the feature on all target platforms (e.g., Android, iOS, web).

## Notes
- Follow REST API design principles for the `/todos/:id` endpoint.
- Secure API endpoints to ensure only authenticated users can edit their own tasks.
- Use `.env` files to securely store API configuration data.
