### ISSUE TITLE
Task: Initialize Koa.js API Project

### ISSUE THREAD

**Issue by chriscoderdr** [chriscoderdr/DoItMorro#3]
# Task: Initialize Koa.js API Project

## Description
Set up the Koa.js API project for the DoItMorro app. This task includes initializing the project, configuring the necessary middleware, and setting up the database connection using Sequelize and PostgreSQL. This API will serve as the backend for managing to-do tasks.

## Labels
- **api**
- **task-management**

### Project Setup
- [x] **Initialize Koa.js Project**:
  - Create a new Koa.js project and initialize `package.json`:
    ```bash
    mkdir doit-morro-api
    cd doit-morro-api
    npm init -y
    ```
  - Install essential Koa.js libraries:
    ```bash
    npm install koa koa-router koa-bodyparser koa-logger koa-cors dotenv
    ```

- [x] **Set Up Basic Server**:
  - Create a `server.js` file and configure Koa to handle requests:
    ```javascript
    const Koa = require('koa');
    const Router = require('koa-router');
    const bodyParser = require('koa-bodyparser');
    const cors = require('@koa/cors');
    const logger = require('koa-logger');
    const dotenv = require('dotenv');

    dotenv.config();

    const app = new Koa();
    const router = new Router();

    app.use(logger());
    app.use(cors());
    app.use(bodyParser());

    router.get('/', (ctx) => {
      ctx.body = { message: 'Welcome to DoItMorro API!' };
    });

    app.use(router.routes()).use(router.allowedMethods());

    const PORT = process.env.PORT || 5000;
    app.listen(PORT, () => {
      console.log(`Server running on port ${PORT}`);
    });
    ```

### Database Setup
- [x] **Install Sequelize and PostgreSQL**:
  - Add Sequelize and PostgreSQL as dependencies:
    ```bash
    npm install sequelize pg pg-hstore
    npm install --save-dev sequelize-cli
    ```

- [x] **Initialize Sequelize**:
  - Use the Sequelize CLI to initialize the project structure:
    ```bash
    npx sequelize-cli init
    ```
  - Configure the `config/config.json` file to connect to the PostgreSQL database:
    ```json
    {
      "development": {
        "username": "postgres",
        "password": "your_password",
        "database": "doit_morro_dev",
        "host": "127.0.0.1",
        "dialect": "postgres"
      }
    }
    ```

- [x] **Create Database**:
  - Create the development database using Sequelize CLI:
    ```bash
    npx sequelize-cli db:create
    ```

### Middleware Configuration
- [x] **Add Middleware**:
  - Configure middleware in `server.js` for:
    - CORS (Cross-Origin Resource Sharing).
    - Request body parsing.
    - Logging requests and responses.

- [x] **Set Up Environment Variables**:
  - Create a `.env` file in the project root:
    ```
    PORT=5000
    DATABASE_URL=postgres://username:password@localhost:5432/doit_morro_dev
    ```

### To-Do Model
- [x] **Define To-Do Sequelize Model**:
  - Create a `to-dos` table model using Sequelize CLI:
    ```bash
    npx sequelize-cli model:generate --name Todo --attributes title:string,description:string,dueDate:date,userId:integer
    ```
  - Migrate the database:
    ```bash
    npx sequelize-cli db:migrate
    ```

### Verification
- [x] **Run and Test API**:
  - Start the server:
    ```bash
    node server.js
    ```
  - Test the base endpoint using a tool like Postman or cURL:
    ```bash
    curl http://localhost:5000/
    ```
  - Confirm the response:
    ```json
    { "message": "Welcome to DoItMorro API!" }
    ```

- [x] **Verify Database Connection**:
  - Ensure the `to-dos` table is successfully created in the database.
  - Test a database query using Sequelize.

## Notes
- Use `dotenv` to manage sensitive configurations securely.
- Include detailed logging for easier debugging during development.
- Follow Sequelize’s documentation for advanced model features if required: [Sequelize Docs](https://sequelize.org/).
- Future enhancements:
  - Add authentication middleware using Firebase Admin SDK.
  - Implement unit tests with Jest and integration tests with Supertest.

**Comment by chriscoderdr** [comment]
sequelize-cli don't quite support typescript so we will first compile to dist and then use sequelize from there, also it won't read the config unless we use module.exports for some reason
