### ISSUE TITLE
Task: Add To-Do - Initialize Koa.js API Project

### ISSUE THREAD

**Issue by chriscoderdr** [chriscoderdr/DoItMorro#31]
# Task: Add To-Do - Initialize Koa.js API Project

## Description
Set up a new Koa.js project manually to serve as the backend for the DoItMorro app. This task includes installing the required dependencies, creating a basic project structure, and configuring essential middleware for routes, request parsing, environment configuration, and authentication.

## Labels
- **api**
- **task-management**

## Checklist
- [ ] **Set Up Project Directory**:
  - Create a new directory for the Koa.js project (e.g., `doit-morro-api`).
  - Initialize a Node.js project:
    ```bash
    yarn init -y
    ```

- [ ] **Install Required Dependencies**:
  - Add Koa and related libraries:
    ```bash
    yarn add koa koa-router koa-bodyparser dotenv
    ```
  - Add Firebase Admin SDK for authentication:
    ```bash
    yarn add firebase-admin
    ```
  - Add development dependencies:
    ```bash
    yarn add -D nodemon eslint
    ```

- [ ] **Configure Basic Project Structure**:
  - Create the following folder structure:
    ```
    /doit-morro-api
    ├── routes/
    ├── middleware/
    ├── models/
    ├── config/
    ├── index.js
    ├── package.json
    ├── .env
    ├── .eslintrc.js
    └── .gitignore
    ```
  - `routes/`: Define API endpoints.
  - `middleware/`: Add custom middleware for authentication and error handling.
  - `models/`: Define database models.
  - `config/`: Add environment-specific configuration logic.

- [ ] **Set Up Environment Variables**:
  - Create a `.env` file in the root directory:
    ```env
    NODE_ENV=development
    PORT=3000
    FIREBASE_ADMIN_SDK_KEY_PATH=./config/firebase-admin-sdk.json
    DATABASE_URL=postgres://username:password@localhost:5432/doit_morro_dev
    ```
  - Ensure the Firebase Admin SDK service account key JSON file is placed at the path specified by `FIREBASE_ADMIN_SDK_KEY_PATH`.

- [ ] **Set Up Middleware**:
  - Add and configure middleware in `index.js`:
    - **Body Parser**:
      ```javascript
      const bodyParser = require('koa-bodyparser');
      app.use(bodyParser());
      ```
    - **CORS Middleware**:
      ```javascript
      const cors = require('@koa/cors');
      app.use(cors());
      ```
    - **Error Handling Middleware**:
      ```javascript
      app.use(async (ctx, next) => {
        try {
          await next();
        } catch (err) {
          ctx.status = err.status || 500;
          ctx.body = { error: err.message };
        }
      });
      ```

- [ ] **Configure Firebase Authentication**:
  - Initialize the Firebase Admin SDK in `index.js`:
    ```javascript
    const admin = require('firebase-admin');
    const serviceAccount = require(process.env.FIREBASE_ADMIN_SDK_KEY_PATH);

    admin.initializeApp({
      credential: admin.credential.cert(serviceAccount),
    });
    ```

- [ ] **Test Basic Setup**:
  - Add a sample route in `routes/index.js`:
    ```javascript
    const Router = require('koa-router');
    const router = new Router();

    router.get('/', (ctx) => {
      ctx.body = { message: 'DoItMorro API is running!' };
    });

    module.exports = router;
    ```
  - Register the route in `index.js`:
    ```javascript
    const Koa = require('koa');
    const app = new Koa();
    const router = require('./routes/index');

    app.use(router.routes());
    app.listen(process.env.PORT, () => {
      console.log(`Server running on http://localhost:${process.env.PORT}`);
    });
    ```
  - Run the server:
    ```bash
    yarn start
    ```
  - Test the endpoint:
    ```bash
    curl http://localhost:3000
    ```

## Dependencies
- Related to #7

## Notes
- Use Firebase Admin SDK for authentication:
  - [Firebase Admin SDK Documentation](https://firebase.google.com/docs/admin/setup)
- Ensure `.env` values and service account credentials are secure and not committed to version control.
- Follow best practices for API structure and scalability.
