### ISSUE TITLE
Task: Add To-Do - Create Add To-Do API Endpoint

### ISSUE THREAD

**Issue by chriscoderdr** [chriscoderdr/DoItMorro#34]
# Task: Add To-Do - Create API Endpoint

## Description
Implement the `POST /todos` endpoint in the Koa.js API using Sequelize to allow users to add new to-do items. Validate the incoming payload for required fields and save the to-do item to the PostgreSQL database, associating it with the authenticated user's `userId`.

## Labels
- **api**
- **task-management**
- **firebase-integration**
- **sequelize**

## Checklist
- [ ] **Define the Route**:
  - Add a new route for `POST /todos` in the `routes/` directory.
  - Register the route in the main Koa.js app configuration.

- [ ] **Validate Payload**:
  - Use middleware to validate the incoming payload:
    - Require a non-empty `title`.
    - Allow optional `description` and `dueDate` fields.
    - Ensure all fields are in the correct data types.
  - Return detailed error messages for invalid payloads with `400 Bad Request` status.

- [ ] **Integrate Authorization Middleware**:
  - Use the Firebase token validation middleware (#32) to authenticate the user.
  - Extract the authenticated `userId` from the request context.

- [ ] **Save to Database**:
  - Use Sequelize's `create` method to insert the new to-do item into the database:
    ```javascript
    const todo = await ToDo.create({
      userId: ctx.state.userId, // Extracted from Firebase middleware
      title: ctx.request.body.title,
      description: ctx.request.body.description || null,
      dueDate: ctx.request.body.dueDate || null,
    });
    ```
  - Automatically handle `createdAt` and `updatedAt` timestamps using Sequelize.

- [ ] **Send Response**:
  - Return a `201 Created` response with the newly created to-do item in JSON format:
    ```javascript
    ctx.status = 201;
    ctx.body = { todo };
    ```
  - Handle errors gracefully:
    - Log unexpected errors for debugging.
    - Return appropriate HTTP status codes (`500 Internal Server Error`, `401 Unauthorized`, etc.).

## Dependencies
- Related to:
  - #8 (Add To-Do User Story)
  - #7 (To-Do Management Epic)
- Dependent on:
  - #31 (Koa.js Initialization)
  - #32 (Firebase Authorization Middleware)
  - #33 (PostgreSQL Setup)

## Notes
- **API Design**:
  - Follow RESTful conventions:
    - `201 Created` for successful creation.
    - `400 Bad Request` for validation failures.
    - `401 Unauthorized` for unauthenticated requests.
  - Validate input rigorously to prevent SQL injection or malformed requests.
  
- **Sequelize Usage**:
  - Leverage Sequelize's validation capabilities to streamline payload validation.
  - Use Sequelize model definitions to ensure data consistency:
    - [Sequelize Documentation](https://sequelize.org/docs/v6/core-concepts/model-querying-basics/)

- **Testing**:
  - Use tools like Postman or cURL to test the endpoint:
    - Test with valid payloads to ensure successful to-do creation.
    - Test with invalid payloads to verify error handling.
  - Mock Firebase token validation during unit tests to simulate authenticated requests.

- **Security**:
  - Securely extract the `userId` from Firebase tokens to associate tasks with authenticated users.
  - Log sensitive operations for audit purposes without exposing user information.
