### ISSUE TITLE
Task: Integrate Mark as Complete Functionality

### ISSUE THREAD

**Issue by chriscoderdr** [chriscoderdr/DoItMorro#37]
# Task: Implement Mark as Complete Functionality

## Description
Implement the functionality to allow users to toggle the completion status of a to-do item. This feature will visually differentiate completed tasks, save changes to the database via the API, and reflect the updated status immediately in the to-do list.

## Labels
- **task-management**
- **mobile-app**
- **api**

### Feature/Functionality Implementation
- [ ] **Enable/Configure Necessary Services**:
  - Confirm that the Sequelize model for `to-dos` includes an `isComplete` field.
  - Ensure the Koa.js backend is set up and operational.

- [ ] **Write Core Functionality**:
  - **Backend**:
    - Add an API endpoint in the Koa.js backend to handle updates to the `isComplete` field:
      ```javascript
      router.put('/todos/:id/status', async (ctx) => {
        const todoId = ctx.params.id;
        const { isComplete } = ctx.request.body;

        const updatedTodo = await Todo.update(
          { isComplete },
          { where: { id: todoId, userId: ctx.state.user.id }, returning: true }
        );

        if (!updatedTodo[1][0]) {
          ctx.status = 404;
          ctx.body = { error: 'To-Do not found' };
          return;
        }

        ctx.status = 200;
        ctx.body = updatedTodo[1][0];
      });
      ```

  - **Frontend**:
    - Define the `updateTodoStatus` mutation in RTK Query:
      ```javascript
      import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

      export const todosApi = createApi({
        reducerPath: 'todosApi',
        baseQuery: fetchBaseQuery({ baseUrl: '/api' }),
        endpoints: (builder) => ({
          updateTodoStatus: builder.mutation({
            query: ({ id, isComplete }) => ({
              url: `/todos/${id}/status`,
              method: 'PUT',
              body: { isComplete },
            }),
          }),
        }),
      });

      export const { useUpdateTodoStatusMutation } = todosApi;
      ```

    - Integrate the mutation into the UI:
      ```javascript
      const [updateTodoStatus, { isLoading, error }] = useUpdateTodoStatusMutation();

      const handleToggleStatus = async (id, isComplete) => {
        try {
          await updateTodoStatus({ id, isComplete }).unwrap();
          alert('Task status updated successfully!');
        } catch (err) {
          console.error('Failed to update task status:', err);
        }
      };
      ```

### Error Handling
- [ ] **Handle and Map Errors**:
  - Display user-friendly messages for common errors, such as:
    - Unauthorized access.
    - Invalid or non-existent task IDs.
    - Network issues.
  - Implement a fallback mechanism to reattempt status updates for transient errors.

### Integration with State Management
- [ ] **Dispatch Redux Actions**:
  - Ensure the Redux store reflects the updated task status:
    - Update the to-do list in the Redux state immediately after a successful API response.

### User Feedback
- [ ] **Provide Feedback on Operation Status**:
  - Add loading spinners or indicators for in-progress updates.
  - Show a success message after the status is updated.
  - Display error messages when the operation fails.

### Testing
- [ ] **Unit Testing**:
  - Write unit tests for the backend API endpoint to verify:
    - Valid requests toggle the `isComplete` field.
    - Proper error handling for invalid task IDs.
  - Write unit tests for the RTK Query `updateTodoStatus` mutation.

- [ ] **Integration Testing**:
  - Ensure the Redux state updates correctly when the API request succeeds or fails.
  - Test the flow of toggling the task status in the app.

- [ ] **End-to-End Testing**:
  - Simulate user interactions for marking a task as complete/incomplete.
  - Verify the entire workflow, including UI updates, API integration, and database changes.

### Verification
- [ ] **Verify State Management Integration**:
  - Ensure tasks marked as complete are correctly reflected in the Redux state.
  - Confirm subsequent features dependent on task status operate correctly.

- [ ] **Check Platform Compatibility**:
  - Validate the functionality works on all targeted platforms (e.g., Android, iOS).

## Notes
- Follow the established design and API standards for consistency.
- Ensure compliance with accessibility guidelines, such as providing keyboard navigation for toggling completion status.
- Document the implementation details and share with the team for reference.
