### ISSUE TITLE
Task: Edit To-Do - Add Edit To-Do API Endpoint

### ISSUE THREAD

**Issue by chriscoderdr** [chriscoderdr/DoItMorro#37]
# Task: Edit To-Do - Add API Endpoint

## Description
Implement the `PUT /todos/:id` endpoint in the Koa.js API using Sequelize to allow users to update their existing to-do items. Validate the incoming payload for required fields and update the to-do item in the PostgreSQL database, ensuring it belongs to the authenticated user.

## Labels
- **api**
- **task-management**
- **firebase-integration**
- **sequelize**

## Checklist
- [ ] **Define the Route**:
  - Add a new route for `PUT /todos/:id` in the `routes/` directory.
  - Ensure the route is properly registered in the Koa.js app.
- [ ] **Validate Payload**:
  - Use middleware or manual validation to check for:
    - Optional `title` field (non-empty if provided).
    - Optional `description` and `due_date` fields (proper data types).
  - Return appropriate error messages for invalid payloads.
- [ ] **Integrate Authorization Middleware**:
  - Use the Firebase token validation middleware (#32) to authenticate the user.
  - Verify that the `user_id` from the token matches the `user_id` of the to-do item.
  - Return a `403 Forbidden` status if the user is not authorized to update the item.
- [ ] **Update Database Record**:
  - Use Sequelize's `update` method to modify the to-do item in the database:
    ```javascript
    const updatedTodo = await ToDo.update(
      { title, description, dueDate },
      { where: { id: todoId, userId: authenticatedUserId } }
    );
    ```
  - Ensure the `updatedAt` field is automatically updated.
  - Handle cases where the to-do item does not exist, returning a `404 Not Found` status.
- [ ] **Send Response**:
  - Return a success response (`200 OK`) with the updated to-do item.
  - Handle and log errors gracefully, returning appropriate HTTP status codes.

## Dependencies
- Related to:
  - #9 (Edit To-Do User Story)
  - #7 (To-Do Management Epic)
- Dependent on:
  - #31 (Koa.js Initialization)
  - #32 (Firebase Authorization Middleware)
  - #33 (PostgreSQL Setup)

## Notes
- Follow RESTful API design principles to ensure consistency:
  - `200 OK` for successful updates.
  - `400 Bad Request` for validation failures.
  - `403 Forbidden` for unauthorized access.
  - `404 Not Found` if the to-do item does not exist.
- Use Sequelize for efficient database operations:
  - [Sequelize Update Query](https://sequelize.org/docs/v6/core-concepts/model-querying-basics/#updating-instances)
- Test thoroughly using tools like Postman or cURL to validate valid and invalid scenarios.
- Ensure detailed logging for all operations to facilitate debugging.
- Use robust error handling to provide clear feedback to users while maintaining security.
