### ISSUE TITLE
Epic: Task Organization

### ISSUE THREAD

**Issue by chriscoderdr** [chriscoderdr/DoItMorro#39]
# Epic: Task Organization

## Description
This epic focuses on implementing task organization features for the DoItMorro app. Users will be able to categorize their tasks using tags, set due dates, and filter tasks for better management and prioritization.

---

## Prerequisites
- The successful completion of **To-Do Management** to ensure core to-do functionalities are in place.
- Extension of the **Sequelize models** to support tagging and due dates.

---

## User Stories

- [ ] **User Story: Assign Tags to Tasks**  
  - **Description**: As a user, I want to assign tags to tasks so that I can categorize them for easy filtering.  
  - **Acceptance Criteria**:  
    - Users can create and assign tags to tasks.  
    - Tasks can display multiple tags.

- [ ] **User Story: Set Due Dates for Tasks**  
  - **Description**: As a user, I want to set due dates for tasks so that I can prioritize what needs to be done.  
  - **Acceptance Criteria**:  
    - Users can add or update a due date.  
    - Tasks with due dates are sorted accordingly.

- [ ] **User Story: Filter Tasks by Tags**  
  - **Description**: As a user, I want to filter tasks by tags so that I can quickly find specific categories of tasks.  yes
  - **Acceptance Criteria**:  
    - Users can select a tag to filter tasks.  
    - Only tasks with the selected tag are displayed.

---

## Labels
- **epics**
- **task-organization**
- **api**
- **mobile-app**

---

## Notes
- **API Enhancements**:
  - Add endpoints for:
    - Managing tags (create, update, delete).
    - Updating due dates for tasks.
    - Filtering tasks by tags.
- **Database and Models**:
  - Extend Sequelize models to include:
    - A `Tags` model.
    - A `ToDoTags` association table for many-to-many relationships between `ToDo` and `Tags`.
    - A `dueDate` field in the `ToDo` model.
  - Example Sequelize model definitions:
    ```javascript
    const Tag = sequelize.define('Tag', {
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true,
        },
        name: {
            type: DataTypes.STRING,
            allowNull: false,
        },
        userId: {
            type: DataTypes.STRING,
            allowNull: false,
        },
    });

    const ToDo = sequelize.define('ToDo', {
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true,
        },
        title: {
            type: DataTypes.STRING,
            allowNull: false,
        },
        description: {
            type: DataTypes.TEXT,
            allowNull: true,
        },
        dueDate: {
            type: DataTypes.DATE,
            allowNull: true,
        },
    });

    ToDo.belongsToMany(Tag, { through: 'ToDoTags' });
    Tag.belongsToMany(ToDo, { through: 'ToDoTags' });
    ```
- **Sequelize Migrations**:
  - Define the schema for `Tags`, `ToDoTags`, and the `dueDate` field in `ToDos`:
    ```javascript
    module.exports = {
        up: async (queryInterface, Sequelize) => {
            await queryInterface.createTable('Tags', {
                id: {
                    type: Sequelize.INTEGER,
                    primaryKey: true,
                    autoIncrement: true,
                },
                name: {
                    type: Sequelize.STRING,
                    allowNull: false,
                },
                userId: {
                    type: Sequelize.STRING,
                    allowNull: false,
                },
                createdAt: {
                    type: Sequelize.DATE,
                    defaultValue: Sequelize.NOW,
                },
                updatedAt: {
                    type: Sequelize.DATE,
                    defaultValue: Sequelize.NOW,
                },
            });

            await queryInterface.createTable('ToDoTags', {
                todoId: {
                    type: Sequelize.INTEGER,
                    references: {
                        model: 'ToDos',
                        key: 'id',
                    },
                },
                tagId: {
                    type: Sequelize.INTEGER,
                    references: {
                        model: 'Tags',
                        key: 'id',
                    },
                },
            });

            await queryInterface.addColumn('ToDos', 'dueDate', {
                type: Sequelize.DATE,
                allowNull: true,
            });
        },
    };
    ```
- **Mobile App Enhancements**:
  - Update the UI to:
    - Support adding and managing tags for tasks.
    - Enable due date selection and display.
    - Implement filtering functionality for tasks by tags.
