### ISSUE TITLE
Task: Initialize Expo Project

### ISSUE THREAD

**Issue by chriscoderdr** [chriscoderdr/DoItMorro#4]
# Task: Initialize Expo Project

## Description
Set up a new React Native project to serve as the frontend for the DoItMorro app. This task includes initializing the project, installing dependencies, and configuring it for Firebase integration and Redux-based state management.

## Labels
- **mobile-app**
- **firebase-integration**
- **state-management**

### Project Setup
- [x] **Set Up React Native Project**:
  - Use Expo to initialize the project:
    ```bash
    npx create-expo-app@latest doit-morro-app
    ```
  - Choose the TypeScript template during setup or add TypeScript manually:
    ```bash
    expo install typescript
    ```

### Dependency Installation
- [x] **Install Core Dependencies**:
  - Add Firebase, Redux, and persistence libraries:
    ```bash
    expo install firebase react-redux @reduxjs/toolkit redux-persist
    ```

### Firebase Initialization
- [x] **Configure Firebase SDK**:
  - Use the Firebase JavaScript SDK for the app.
  - Set up the Firebase configuration in the app:
    ```javascript
    import { initializeApp } from "firebase/app";

    const firebaseConfig = {
      apiKey: "your-api-key",
      authDomain: "your-app.firebaseapp.com",
      projectId: "your-project-id",
      storageBucket: "your-app.appspot.com",
      messagingSenderId: "your-messaging-sender-id",
      appId: "your-app-id",
    };

    const app = initializeApp(firebaseConfig);
    ```

### Redux and State Management
- [x] **Integrate Redux**:
  - Create a Redux slice for managing authentication state:
    ```javascript
    import { createSlice } from "@reduxjs/toolkit";

    const authSlice = createSlice({
      name: "auth",
      initialState: { isLoggedIn: false, user: null },
      reducers: {
        setUser(state, action) {
          state.isLoggedIn = !!action.payload;
          state.user = action.payload;
        },
        clearUser(state) {
          state.isLoggedIn = false;
          state.user = null;
        },
      },
    });

    export const { setUser, clearUser } = authSlice.actions;
    ```
- [x] **Connect Firebase Authentication with Redux**:
  - Use Firebase's `onAuthStateChanged` to update the Redux store:
    ```javascript
    import { getAuth, onAuthStateChanged } from "firebase/auth";
    const auth = getAuth();

    onAuthStateChanged(auth, (user) => {
      if (user) {
        store.dispatch(setUser(user));
      } else {
        store.dispatch(clearUser());
      }
    });
    ```

- [x] **Persist Redux State**:
  - Configure `redux-persist` to persist the authentication state:
    ```javascript
    import AsyncStorage from "@react-native-async-storage/async-storage";
    import { persistReducer, persistStore } from "redux-persist";

    const persistConfig = {
      key: "root",
      storage: AsyncStorage,
    };

    const persistedReducer = persistReducer(persistConfig, rootReducer);
    ```

### Verification
- [x] **Test Firebase Authentication Integration**:
  - Test user sign-in and ensure proper state updates:
    ```javascript
    import { getAuth, signInWithEmailAndPassword } from "firebase/auth";

    const auth = getAuth();
    signInWithEmailAndPassword(auth, "test@example.com", "password123")
      .then((userCredential) => console.log("Login successful", userCredential))
      .catch((error) => console.error("Login failed", error));
    ```

- [x] **Run and Verify Project Setup**:
  - Start the project to ensure proper setup:
    ```bash
    npx expo start
    ```
  - Check for any errors or warnings and resolve them.

## Notes
- Ensure compatibility with Expo Go by using the Firebase JavaScript SDK.
- Avoid using platform-specific Firebase configuration files (`google-services.json` and `GoogleService-Info.plist`) as they are not needed for the JavaScript SDK.
- Store sensitive Firebase configuration keys securely in `.env` files.
- Follow Expo's official documentation for guidance: [Expo Documentation](https://docs.expo.dev/).

**Comment by chriscoderdr** [comment]
Had a little trouble with persistence of firebase but got to fix it, used diference persistence for web and mobile, there is a ts error so added ignore just to that line in the firebase initialization

**Comment by chriscoderdr** [comment]
I also added LeftHook and eslint and pretty, it was not in the specs but I figured out it's not bad to thing to have

**Comment by chriscoderdr** [comment]
merged in #43
