### ISSUE TITLE
 Epic: Collaboration (Future Feature)

### ISSUE THREAD

**Issue by chriscoderdr** [chriscoderdr/DoItMorro#40]
# Epic: Collaboration (Future Feature)

## Description
This epic focuses on implementing collaboration features for the DoItMorro app. Users will be able to share tasks with others, assign permissions, and receive notifications for updates to shared tasks. This functionality aims to enhance teamwork and task-sharing capabilities.

---

## Prerequisites
- The successful completion of **Epic: To-Do Management** to ensure task management is fully functional.
- Extending the **Sequelize models** to support collaboration features, including task sharing, permissions, and notifications.

---

## User Stories

- [ ] **User Story: Invite Collaborators to Tasks**  
  - **Description**: As a user, I want to invite others to collaborate on a task so that we can work on it together.  
  - **Acceptance Criteria**:  
    - Users can add collaborators by their email address.  
    - Invited collaborators receive an invitation via email or app notification.  

- [ ] **User Story: Set Permissions for Collaborators**  
  - **Description**: As a user, I want to set permissions for collaborators (e.g., viewer, editor) so that I can control their access.  
  - **Acceptance Criteria**:  
    - Users can assign permission levels to collaborators.  
    - Collaborators' actions are restricted based on their permissions (e.g., viewers cannot edit tasks).  

- [ ] **User Story: Notifications for Shared Task Updates**  
  - **Description**: As a user, I want to be notified when a collaborator updates a shared task so that I stay informed.  
  - **Acceptance Criteria**:  
    - Notifications are sent for edits, completions, or comments on shared tasks.  
    - Notifications can be marked as read or unread.  

---

## Labels
- **epics**
- **collaboration**
- **api**
- **mobile-app**

---

## Notes
- **API Enhancements**:
  - Add endpoints for:
    - Managing collaborators (invite, update, remove).
    - Setting and updating collaborator permissions.
    - Sending and managing notifications for shared task updates.
- **Database and Models**:
  - Extend Sequelize models to support collaboration and notifications:
    - Define a `Collaborator` model for managing task-sharing relationships:
      ```javascript
      const Collaborator = sequelize.define('Collaborator', {
          id: {
              type: DataTypes.INTEGER,
              primaryKey: true,
              autoIncrement: true,
          },
          taskId: {
              type: DataTypes.INTEGER,
              references: { model: 'ToDos', key: 'id' },
              allowNull: false,
          },
          collaboratorEmail: {
              type: DataTypes.STRING,
              allowNull: false,
          },
          role: {
              type: DataTypes.STRING, // 'viewer', 'editor', etc.
              allowNull: false,
          },
      });
      ```
    - Define a `Notification` model for managing task update notifications:
      ```javascript
      const Notification = sequelize.define('Notification', {
          id: {
              type: DataTypes.INTEGER,
              primaryKey: true,
              autoIncrement: true,
          },
          taskId: {
              type: DataTypes.INTEGER,
              references: { model: 'ToDos', key: 'id' },
              allowNull: false,
          },
          userId: {
              type: DataTypes.STRING,
              allowNull: false,
          },
          message: {
              type: DataTypes.TEXT,
              allowNull: false,
          },
          status: {
              type: DataTypes.STRING,
              defaultValue: 'unread', // 'read', 'unread'
          },
      });
      ```

- **Mobile App Enhancements**:
  - Update the UI to:
    - Allow users to invite collaborators and manage permissions.
    - Display notifications for task updates in a user-friendly manner.
  - Ensure real-time updates using Firebase or another notification system.
- **Sequelize Migrations**:
  - Define migrations for creating the `Collaborators` and `Notifications` tables:
    ```javascript
    module.exports = {
        up: async (queryInterface, Sequelize) => {
            await queryInterface.createTable('Collaborators', {
                id: {
                    type: Sequelize.INTEGER,
                    primaryKey: true,
                    autoIncrement: true,
                },
                taskId: {
                    type: Sequelize.INTEGER,
                    references: {
                        model: 'ToDos',
                        key: 'id',
                    },
                    allowNull: false,
                },
                collaboratorEmail: {
                    type: Sequelize.STRING,
                    allowNull: false,
                },
                role: {
                    type: Sequelize.STRING, // 'viewer', 'editor', etc.
                    allowNull: false,
                },
                createdAt: {
                    type: Sequelize.DATE,
                    defaultValue: Sequelize.NOW,
                },
                updatedAt: {
                    type: Sequelize.DATE,
                    defaultValue: Sequelize.NOW,
                },
            });

            await queryInterface.createTable('Notifications', {
                id: {
                    type: Sequelize.INTEGER,
                    primaryKey: true,
                    autoIncrement: true,
                },
                taskId: {
                    type: Sequelize.INTEGER,
                    references: {
                        model: 'ToDos',
                        key: 'id',
                    },
                    allowNull: false,
                },
                userId: {
                    type: Sequelize.STRING,
                    allowNull: false,
                },
                message: {
                    type: Sequelize.TEXT,
                    allowNull: false,
                },
                status: {
                    type: Sequelize.STRING,
                    defaultValue: 'unread', // 'read', 'unread'
                },
                createdAt: {
                    type: Sequelize.DATE,
                    defaultValue: Sequelize.NOW,
                },
                updatedAt: {
                    type: Sequelize.DATE,
                    defaultValue: Sequelize.NOW,
                },
            });
        },
    };
    ```
