### ISSUE TITLE
Task: Delete To-Do - Add API Endpoint

### ISSUE THREAD

**Issue by chriscoderdr** [chriscoderdr/DoItMorro#45]
# Task: Delete To-Do - Add API Endpoint #45

## Description
Implement the `DELETE /todos/:id` endpoint in the Koa.js API to allow users to delete their to-do items. Validate the `id` parameter to ensure it corresponds to an existing to-do item and is owned by the authenticated user. Use Sequelize to securely and efficiently remove the specified to-do item from the PostgreSQL database.

## Labels
- **api**
- **task-management**
- **firebase-integration**
- **sequelize**

## Checklist
- [ ] **Define the Route**:
  - Add a new route for `DELETE /todos/:id` in the `routes/` directory.
  - Ensure the route is properly registered in the Koa.js app.
- [ ] **Validate ID Parameter**:
  - Validate that the `id` parameter exists and corresponds to a valid to-do item using Sequelize's `findOne` method.
  - Return a `404 Not Found` response if the to-do item does not exist.
- [ ] **Integrate Authorization Middleware**:
  - Use the Firebase token validation middleware (#32) to authenticate the user.
  - Extract the `user_id` from the authenticated token.
  - Validate ownership by ensuring the `user_id` in the token matches the `userId` of the to-do item in the database.
  - Return a `403 Forbidden` response if the user is not authorized to delete the item.
- [ ] **Delete from Database**:
  - Use Sequelize's `destroy` method to permanently delete the to-do item with the specified `id` and `userId`.
  - Example query:
    ```javascript
    await ToDo.destroy({
      where: {
        id: todoId,
        userId: authenticatedUserId,
      },
    });
    ```
  - Ensure the deletion does not leave orphaned references in the database.
- [ ] **Send Response**:
  - Return a `200 OK` response indicating the to-do item was successfully deleted.
  - Include a success message or the deleted item's details in the response for confirmation.
  - Handle and log errors gracefully, returning appropriate HTTP status codes.

## Dependencies
- Related to:
  - #10 (Delete To-Do User Story)
  - #7 (To-Do Management Epic)
- Dependent on:
  - #31 (Koa.js Initialization)
  - #32 (Firebase Authorization Middleware)
  - #33 (PostgreSQL Setup)

## Notes
- Follow RESTful API design principles for consistency:
  - `200 OK` for successful deletion.
  - `404 Not Found` if the to-do item does not exist.
  - `403 Forbidden` for unauthorized deletion attempts.
- Ensure robust error handling and detailed logging to facilitate debugging.
- Use Sequelize for efficient query handling and integration with PostgreSQL:
  - [Sequelize Model Querying](https://sequelize.org/docs/v6/core-concepts/model-querying-basics/)
  - [Sequelize Destroy](https://sequelize.org/docs/v6/core-concepts/model-querying-basics/#destroying-data)
- Test thoroughly using tools like Postman or cURL to validate both valid and invalid scenarios.
