### ISSUE TITLE
Task: Delete To-Do - Database Delete Logic

### ISSUE THREAD

**Issue by chriscoderdr** [chriscoderdr/DoItMorro#47]
# Task: Delete To-Do - Database Delete Logic

## Description
Implement the database logic to delete a to-do item using Sequelize. This task ensures the deletion of to-do items is permanent and does not leave orphaned references in the database.

## Labels
- **api**
- **task-management**
- **sequelize**

## Checklist
- [ ] **Define the Model and Relationships**:
  - Ensure the `ToDo` model is properly defined with relationships to other models (if any).
  - Validate the `userId` relationship to associate to-dos with authenticated users.
- [ ] **Write the Delete Query**:
  - Use Sequelize to write a query that deletes a to-do item by its `id`.
  - Ensure the query includes a condition to match the authenticated user's `userId`.
  - Example:
    ```javascript
    await ToDo.destroy({
      where: {
        id: todoId,
        userId: authenticatedUserId
      }
    });
    ```
- [ ] **Validate Deletion**:
  - Confirm the to-do item exists before attempting deletion.
  - Throw an error or return an appropriate response if the to-do does not exist or does not belong to the user.
- [ ] **Handle Errors**:
  - Return a `404 Not Found` error if the item does not exist.
  - Return a `403 Forbidden` error if the user attempts to delete a to-do they do not own.
- [ ] **Test the Query**:
  - Test the deletion logic with:
    - Valid `id` and `userId`.
    - Non-existent `id`.
    - Mismatched `userId`.

## Dependencies
- Related to:
  - #45
  - #46
- Dependent on:
  - Sequelize setup and configuration (#33).

## Notes
- Ensure the `ToDo` model's `id` field uses a `PRIMARY KEY` constraint for efficient lookups.
- Use Sequelize's built-in transaction support to handle complex deletions if necessary.
- Follow best practices for error handling to ensure secure and clear feedback for users.
- Refer to the official Sequelize documentation for guidance:
  - [Sequelize Model Basics](https://sequelize.org/docs/v6/core-concepts/model-basics/)
  - [Sequelize Querying](https://sequelize.org/docs/v6/core-concepts/model-querying-basics/)
