### ISSUE TITLE
Task: Edit To-Do - Add Edit To-Do API Endpoint

### ISSUE THREAD

**Issue by chriscoderdr** [chriscoderdr/DoItMorro#48]
# Task: Add To-Do - Create API Endpoint

## Description
Implement the `POST /todos` endpoint in the Koa.js API using Sequelize to allow users to add new to-do items. This task includes validating the incoming payload, saving the to-do item to the PostgreSQL database, and handling edge cases. The database logic for updating `updatedAt` timestamps and checking ownership is integrated here.

## Labels
- **api**
- **task-management**
- **firebase-integration**
- **sequelize**

## Checklist
- [ ] **Define the Route**:
  - Add a new route for `POST /todos` in the `routes/` directory.
  - Ensure the route is properly registered in the Koa.js app.

- [ ] **Validate Payload**:
  - Use middleware or manual validation to check for:
    - Non-empty `title`.
    - Optional `description` and `due_date` fields.
    - Proper data types for all fields.
  - Return appropriate error messages for invalid payloads.

- [ ] **Integrate Authorization Middleware**:
  - Use the Firebase token validation middleware (#32) to authenticate the user.
  - Extract the `user_id` from the request context.

- [ ] **Save to Database with Sequelize**:
  - Use Sequelize's `create` method to insert the new to-do item into the database:
    ```javascript
    const todo = await ToDo.create({
      userId: authenticatedUserId,
      title: req.body.title,
      description: req.body.description,
      dueDate: req.body.dueDate,
    });
    ```
  - Automatically handle `createdAt` and `updatedAt` timestamps using Sequelize's built-in functionality.
  - Handle edge cases:
    - Ensure non-existent to-do items return a `404 Not Found` response.
    - Prevent unauthorized users from updating tasks they do not own with a `403 Forbidden` response.

- [ ] **Send Response**:
  - Return a success response (`201 Created`) with the newly created to-do item.
  - Handle and log errors gracefully, returning appropriate HTTP status codes.

## Dependencies
- Related to:
  - #8 (Add To-Do User Story)
  - #7 (To-Do Management Epic)
- Dependent on:
  - #31 (Koa.js Initialization)
  - #32 (Firebase Authorization Middleware)
  - #33 (PostgreSQL Setup)

## Notes
- Follow RESTful API design principles for consistency:
  - `201 Created` for successful creation.
  - `400 Bad Request` for validation failures.
  - `401 Unauthorized` for unauthenticated requests.
- Use Sequelize for database operations to ensure consistency and efficiency:
  - [Sequelize Model Querying](https://sequelize.org/docs/v6/core-concepts/model-querying-basics/)
- Test thoroughly using tools like Postman or cURL to validate both valid and invalid scenarios.
- Ensure the `user_id` is securely extracted from the Firebase token and associated with the new to-do item.
- Log all operations for traceability and debugging.
